In [34]:
import modularize
import gz_to_csv
reload(gz_to_csv)

In [2]:
load = modularize.Load_Price_Ret(file_dir='/media/sf_ubuntu_share/corr_output/return/20180416/0s/')

In [4]:
ret0=load.load_gz_file(dir='/media/sf_ubuntu_share/corr_output/return/20180416/0s/no_resample.dat.gz')

In [7]:
ret0[['cs0','ru0']]

                              cs0       ru0
2018-04-16 09:00:00.000  0.000000  0.000000
2018-04-16 09:00:00.500  0.000000  0.000000
2018-04-16 09:00:01.000  0.000000  0.000000
2018-04-16 09:00:01.500 -0.000468  0.000000
2018-04-16 09:00:02.000  0.000000 -0.000438
2018-04-16 09:00:02.500  0.000468  0.000000
2018-04-16 09:00:03.000  0.000000 -0.000438
2018-04-16 09:00:03.500  0.000000  0.000000
2018-04-16 09:00:04.000  0.000000  0.000000
2018-04-16 09:00:04.500 -0.000468  0.000000
2018-04-16 09:00:05.000  0.000000  0.000000
2018-04-16 09:00:05.500  0.000468 -0.000438
2018-04-16 09:00:06.000 -0.000234  0.000438
2018-04-16 09:00:06.500 -0.000234  0.000000
2018-04-16 09:00:07.000  0.000000 -0.000438
2018-04-16 09:00:07.500  0.000000  0.000000
2018-04-16 09:00:08.000  0.000000  0.000000
2018-04-16 09:00:08.500  0.000000  0.000000
2018-04-16 09:00:09.000 -0.000468  0.000000
2018-04-16 09:00:09.500  0.000000  0.000438
2018-04-16 09:00:10.000 -0.000468 -0.000876
2018-04-16 09:00:10.500  0.000000  0.000219
2018-04-16 09:00:11.000  0.000000 -0.000219
2018-04-16 09:00:11.500  0.000000  0.000000
2018-04-16 09:00:12.000  0.000000 -0.000439
2018-04-16 09:00:12.500  0.000000  0.000000
2018-04-16 09:00:13.000  0.000000  0.000439
2018-04-16 09:00:13.500  0.000000  0.000000
2018-04-16 09:00:14.000  0.000000  0.000439
2018-04-16 09:00:14.500  0.000000  0.000000
...                           ...       ...
2018-04-16 14:59:45.500  0.000000  0.000000
2018-04-16 14:59:46.000  0.000000  0.000000
2018-04-16 14:59:46.500  0.000000  0.000000
2018-04-16 14:59:47.000  0.000000  0.000000
2018-04-16 14:59:47.500  0.000000  0.000000
2018-04-16 14:59:48.000  0.000000  0.000000
2018-04-16 14:59:48.500  0.000000  0.000000
2018-04-16 14:59:49.000  0.000000  0.000000
2018-04-16 14:59:49.500  0.000000  0.000000
2018-04-16 14:59:50.000  0.000470  0.000000
2018-04-16 14:59:50.500  0.000235  0.000000
2018-04-16 14:59:51.000  0.000000  0.000449
2018-04-16 14:59:51.500  0.000000 -0.000449
2018-04-16 14:59:52.000  0.000000  0.000449
2018-04-16 14:59:52.500  0.000000  0.000000
2018-04-16 14:59:53.000  0.000000  0.000000
2018-04-16 14:59:53.500  0.000000  0.000000
2018-04-16 14:59:54.000  0.000000  0.000000
2018-04-16 14:59:54.500  0.000000  0.000000
2018-04-16 14:59:55.000 -0.000235  0.000000
2018-04-16 14:59:55.500  0.000000  0.000000
2018-04-16 14:59:56.000 -0.000470 -0.000449
2018-04-16 14:59:56.500  0.000000  0.000000
2018-04-16 14:59:57.000  0.000000  0.000000
2018-04-16 14:59:57.500  0.000000  0.000000
2018-04-16 14:59:58.000  0.000000  0.000000
2018-04-16 14:59:58.500  0.000000  0.000000
2018-04-16 14:59:59.000  0.000470  0.000000
2018-04-16 14:59:59.500  0.000235  0.000000
2018-04-16 15:00:00.000 -0.000235  0.000449

[28799 rows x 2 columns]

In [37]:
gz2csv = gz_to_csv.Gz2Csv(dir = '/media/sf_ubuntu_share/corr_output/price/20180416/ru0/')

In [42]:
gz2csv.gz2csv()

In [43]:
gz2csv.delete_generated_file()

generated files and folders deleted!

In [33]:
gz2csv.generated_file

['/media/sf_ubuntu_share/corr_output/price/20180416/ru0/generated_csv/period_0s.csv',
 '/media/sf_ubuntu_share/corr_output/price/20180416/ru0/generated_csv/period_1s.csv',
 '/media/sf_ubuntu_share/corr_output/price/20180416/ru0/generated_csv/period_5s.csv',
 '/media/sf_ubuntu_share/corr_output/price/20180416/ru0/generated_csv/period_0s.csv',
 '/media/sf_ubuntu_share/corr_output/price/20180416/ru0/generated_csv/period_1s.csv',
 '/media/sf_ubuntu_share/corr_output/price/20180416/ru0/generated_csv/period_5s.csv']

In [8]:
raw = load.loaddata('20180416')

In [9]:
ru = raw[raw['ticker']=='ru1809']

In [10]:
ru

,ticker,bid_price,bid_volume,ask_price,ask_volume,last_price,last_volume,open_interest,turnover
2018-04-16 09:00:00.500,ru1809,11420.0,200,11425.0,6,11425.0,163810,441412,1.881356e+10
2018-04-16 09:00:01.000,ru1809,11420.0,121,11425.0,112,11425.0,164042,441558,1.884005e+10
2018-04-16 09:00:01.500,ru1809,11420.0,39,11425.0,223,11420.0,164354,441624,1.887569e+10
2018-04-16 09:00:02.000,ru1809,11415.0,131,11420.0,161,11415.0,164508,441702,1.889328e+10
2018-04-16 09:00:02.500,ru1809,11415.0,50,11420.0,151,11415.0,164698,441848,1.891497e+10
2018-04-16 09:00:03.000,ru1809,11410.0,132,11415.0,11,11410.0,164944,441950,1.894305e+10
2018-04-16 09:00:03.500,ru1809,11410.0,65,11415.0,3,11420.0,165188,442036,1.897089e+10
2018-04-16 09:00:04.000,ru1809,11410.0,24,11415.0,3,11410.0,165368,442086,1.899144e+10
2018-04-16 09:00:04.500,ru1809,11410.0,13,11415.0,14,11415.0,165426,442080,1.899806e+10
2018-04-16 09:00:05.000,ru1809,11410.0,2,11415.0,34,11410.0,165498,442072,1.900627e+10
2018-04-16 09:00:05.500,ru1809,11405.0,255,11410.0,18,11410.0,165648,442184,1.902338e+10
2018-04-16 09:00:06.000,ru1809,11410.0,67,11415.0,83,11410.0,165844,442274,1.904574e+10
2018-04-16 09:00:06.500,ru1809,11410.0,33,11415.0,84,11415.0,165964,442298,1.905943e+10
2018-04-16 09:00:07.000,ru1809,11405.0,200,11410.0,33,11410.0,166184,442402,1.908454e+10
2018-04-16 09:00:07.500,ru1809,11405.0,193,11410.0,48,11410.0,166236,442408,1.909047e+10
2018-04-16 09:00:08.000,ru1809,11405.0,191,11410.0,60,11405.0,166274,442402,1.909481e+10
2018-04-16 09:00:08.500,ru1809,11405.0,151,11410.0,71,11405.0,166366,442470,1.910530e+10
2018-04-16 09:00:09.000,ru1809,11405.0,21,11410.0,86,11405.0,166686,442470,1.914180e+10
2018-04-16 09:00:09.500,ru1809,11410.0,10,11415.0,70,11405.0,167032,442334,1.918127e+10
2018-04-16 09:00:10.000,ru1809,11400.0,457,11405.0,1,11405.0,167212,442450,1.920180e+10
2018-04-16 09:00:10.500,ru1809,11400.0,464,11410.0,132,11410.0,167266,442442,1.920796e+10
2018-04-16 09:00:11.000,ru1809,11400.0,385,11405.0,4,11400.0,167448,442408,1.922871e+10
2018-04-16 09:00:11.500,ru1809,11400.0,100,11405.0,7,11400.0,168102,442574,1.930327e+10
2018-04-16 09:00:12.000,ru1809,11395.0,57,11400.0,41,11400.0,168366,442626,1.933336e+10
2018-04-16 09:00:12.500,ru1809,11395.0,55,11400.0,2,11395.0,168970,442870,1.940224e+10
2018-04-16 09:00:13.000,ru1809,11400.0,97,11405.0,34,11400.0,169040,442878,1.941022e+10
2018-04-16 09:00:13.500,ru1809,11400.0,99,11405.0,11,11400.0,169148,442900,1.942254e+10
2018-04-16 09:00:14.000,ru1809,11405.0,21,11410.0,50,11405.0,169200,442940,1.942847e+10
2018-04-16 09:00:14.500,ru1809,11405.0,2,11410.0,76,11405.0,169298,442980,1.943964e+10
2018-04-16 09:00:15.000,ru1809,11400.0,60,11410.0,88,11400.0,169378,442956,1.944877e+10
...,...,...,...,...,...,...,...,...,...
2018-04-16 14:59:45.500,ru1809,11130.0,172,11135.0,18,11130.0,744368,488918,8.395637e+10
2018-04-16 14:59:46.000,ru1809,11130.0,170,11135.0,20,11135.0,744386,488912,8.395838e+10
2018-04-16 14:59:46.500,ru1809,11130.0,177,11135.0,23,11135.0,744396,488908,8.395949e+10
2018-04-16 14:59:47.000,ru1809,11130.0,176,11135.0,30,11135.0,744400,488910,8.395993e+10
2018-04-16 14:59:47.500,ru1809,11130.0,119,11135.0,31,11130.0,744536,488922,8.397507e+10
2018-04-16 14:59:48.000,ru1809,11130.0,127,11135.0,35,11135.0,744552,488908,8.397685e+10
2018-04-16 14:59:48.500,ru1809,11130.0,104,11135.0,43,11135.0,744628,488852,8.398531e+10
2018-04-16 14:59:49.000,ru1809,11130.0,125,11135.0,52,11135.0,744648,488842,8.398754e+10
2018-04-16 14:59:49.500,ru1809,11130.0,127,11135.0,35,11135.0,744692,488810,8.399244e+10
2018-04-16 14:59:50.000,ru1809,11130.0,132,11135.0,33,11130.0,744714,488806,8.399489e+10
2018-04-16 14:59:50.500,ru1809,11130.0,118,11135.0,5,11135.0,744786,488800,8.400290e+10
2018-04-16 14:59:51.000,ru1809,11135.0,6,11140.0,136,11130.0,744838,488778,8.400869e+10
2018-04-16 14:59:51.500,ru1809,11130.0,121,11135.0,4,11130.0,744902,488752,8.401582e+10
2018-04-16 14:59:52.000,ru1809,11135.0,4,11140.0,100,11140.0,744964,488712,8.402272e+10
2018-04-16 14:59:52.500,ru1809,11135.0,15,11140.0,103,11135.0,745002,488702,8.402695e+10
2018-04-16 14:59:53.000,ru1809,11135.0,18,11140.0,103,11135.0,745024,488682,8.402940e+10
2018-04-16 14:59:53.500,ru1809,11135.0,12,11140.0,101,11135.0,745046,488668,8.403185e+10
2018-04-16 14:59:54.000,ru1809,11135.0,9,11140.0,99,11140.0,745074,488658,8.403497e+10
2018-04-16 14:59:54.500,ru1809,11135.0,61,11140.0,97,11140.0,745094,488648,8.403720e+10
2018-04-16 14:59:55.000,ru1809,11135.0,58,11140.0,90,11135.0,745122,488632,8.404032e+10
2018-04-16 14:59:55.500,ru1809,11135.0,43,11140.0,81,11135.0,745176,488610,8.404633e+10
2018-04-16 14:59:56.000,ru1809,11130.0,64,11135.0,51,11135.0,745316,488504,8.406192e+10
2018-04-16 14:59:56.500,ru1809,11130.0,50,11135.0,42,11130.0,745380,488474,8.406904e+10
2018-04-16 14:59:57.000,ru1809,11130.0,52,11135.0,31,11135.0,745402,488454,8.407149e+10
2018-04-16 14:59:57.500,ru1809,11130.0,35,11135.0,22,11130.0,745446,488432,8.407639e+10
2018-04-16 14:59:58.000,ru1809,11130.0,27,11135.0,16,11135.0,745480,488440,8.408018e+10
2018-04-16 14:59:58.500,ru1809,11130.0,25,11135.0,9,11130.0,745504,488438,8.408285e+10
2018-04-16 14:59:59.000,ru1809,11130.0,23,11135.0,7,11135.0,745516,488430,8.408419e+10
2018-04-16 14:59:59.500,ru1809,11130.0,12,11135.0,1,11130.0,745554,488410,8.408842e+10
2018-04-16 15:00:00.000,ru1809,11135.0,2,11140.0,82,11135.0,745558,488406,8.408886e+10